[project]
name = "kpub"
version = "0.1.0"
description = "enables an institution to keep track of it's scientific publications in an easy way."
authors = [
    {name = "Tyler Tucker",email = "tylertucker202@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
  "pyyaml",
  "requests",
  "jinja2",
  "textract-py3",
  "matplotlib",
  "pymongo",
  "bokeh",
  "openpyxl"
]


[tool.setuptools]
packages = ["kpub"]

[tool.setuptools.package-dir]
"kpub" = "src"

[tool.setuptools.package-data]
kpub = ["config/*.yaml", "templates/*.md"]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"
