{
  #Unique identifier for this mission/facility. Used for prepending to output filenames, etc.
  "prepend": "kepler",

  #ADS API Key
  #todo: only need this if we switch to querying ADS directly (otherwise shoudl be in ~/.ads/dev_key per ads module instructions)
  "ADS_API_KEY": "",

  #Missions and sciences groupings
  "missions": ['kepler', 'k2'],
  "sciences": ['exoplanets', 'astrophysics'],

  #ADS query terms list.  All will be joined with a space.
  #NOTE: Do not include pubdate or year here since this is an input to run kpub
  "ads_query_terms_group_1" : [
    '(ack:"Kepler mission" OR ack:"K2 mission" OR ack:"Kepler team" OR ack:"K2 team")',
    '-ack:"partial support from"',
    'property:"refereed"',
    'database:astronomy'
  ],

  #ADS query terms list.  All will be joined with a space.
  #NOTE: Do not include pubdate or year here since this is an input to run kpub
  "ads_query_terms_group_2" : [
    'property:"refereed"',
    '(abs:"Kepler"
      OR abs:"K2"
      OR abs:"KIC"
      OR abs:"EPIC"
      OR abs:"KOI"
      OR abs:"8462852"
      OR abs:"1145+017"
      OR abs:"NGC 6791"
      OR abs:"NGC 6819"
      OR title:"Kepler"
      OR title:"K2"
      OR title:"8462852"
      OR title:"1145+017"
      OR full:"K2-ESPRINT"
      OR full:"Kepler photometry"
      OR full:"K2 photometry"
      OR full:"Kepler lightcurve"
      OR full:"K2 lightcurve")',
    'database:astronomy'
  ],

  # Dict of keywords to highlight in the title and abstract (color options: RED, GREEN, YELLOW, BLUE, PURPLE, CYAN)
  "colors": {
    'KEPLER': "BLUE",
    'KIC': "BLUE",
    'KOI': "BLUE",
    '8462852': "BLUE",  # KIC ID of Tabby's star
    'K2': "RED",
    'EPIC': "RED",
    '1145+017': "RED",  # Disintegrating WD in K2
    'PLANET': "YELLOW"
  }
}