{
  #Unique identifier for this mission/facility. Used for prepending to output filenames, etc.
  "prepend": "keck",

  #ADS API Key
  #todo: only need this if we switch to querying ADS directly (otherwise shoudl be in ~/.ads/dev_key per ads module instructions)
  "ADS_API_KEY": "",

  #Missions and sciences groupings
  #NOTE: missions is the main grouping and is required. Sciences is optional.
  "missions": ['keck'],
  "sciences": [],

  #ADS query include terms list (searching full article text) 
  "ads_includes": [
    'keck'
  ],

  #ADS query exclude terms list. Papers with any of these in full text will be excluded. 
  "ads_excludes": [
    "BICEP",
    "NUANCE",
    "keck foundation",
    "keck array",
  ],

  #ADS query extra terms list.  
  "ads_extra": [
    #'-bibcode:"keck"',
    'property:"refereed"'
  ],

  #Specific instrument assocations to look for
  "instruments": [
    'DEIMOS',
    'ESI',
    'HIRES',
    'KCWI',
    'LRIS',
    'MOSFIRE',
    'NIRC2',
    'NIRES',
    'NIRSPEC',
    'OSIRIS',
    'AO',
    'LGS',
    'NGS',
  ],

  #Archives strings to look for to indicate was archived
  "archive": [
    'KOA', 
    'Keck Observatory Archive',
    'Keck data archive'
  ],

  # Dict of keywords to highlight in the title and abstract (color options: RED, GREEN, YELLOW, CYAN, PURPLE, CYAN)
  "colors": {
    'KECK': "GREEN",
    'DEIMOS': "CYAN",
    'ESI': "CYAN",
    'HIRES': "CYAN",
    'KCWI': "CYAN",
    'LRIS': "CYAN",
    'MOSFIRE': "CYAN",
    'NIRC2': "CYAN",
    'NIRES': "CYAN",
    'NIRSPEC': "CYAN",
    'OSIRIS': "CYAN",
    'LGS': "CYAN",
    'NGS': "CYAN",
    'AO': "CYAN",
    'KOA': "YELLOW",
    'Archive': "YELLOW"  #note: can't conflict with "KECK" above
  },

  #Affiliation category types with search strings to identify.  "other" is default category.
  #NOTE: If all caps, then search is case-sensitive.
  "aff_defs": [
    {
      "type": "keck",
      "strings": [
        "keck",
        "WMKO",
        "California Institute of Technology",
        "Caltech",
        "CIT",
        "University of California",
        #"UCB", #This matches UCB (U Colorado at Boulder)
        "UCD",
        "UCI",
        "UCLA",
        "UCR",
        "UCSB",
        "UCSC",
        "UCSD",
        "USRA",
        "University of Hawaii",
        "University of Hawai'i",
        "University of Hawai`i",
        "University of Hawai‘i",
        "Manoa",
        "ANU",
        "Australian National University",
        "Northwestern",
        "Swinburne",
        "Yale",
        "JPL",
        "Jet Propulsion Laboratory",
      ]
    },
    {
      "type": "usa",
      "strings": [
        "USA",
        "United States of America",
        "NASA",
        "National Aeronautics and Space Administration",
      ]
    },
  ],

}

