{
  #Unique identifier for this mission/facility. Used for prepending to output filenames, etc.
  "prepend": "keck",

  #ADS API Key
  #todo: only need this if we switch to querying ADS directly (otherwise shoudl be in ~/.ads/dev_key per ads module instructions)
  "ADS_API_KEY": "",

  #Missions and sciences groupings
  #NOTE: missions is the main grouping and is required. Sciences is optional.
  "missions": ['keck'],
  "sciences": [],

  #ADS query include terms list (searching full article text) 
  "ads_includes": [
    'keck'
  ],

  #ADS query exclude terms list. Papers with any of these in full text will be excluded. 
  "ads_excludes": [
    "BICEP",
    "NUANCE",
    "keck foundation",
    "keck array",
  ],

  #ADS query extra terms list.  
  "ads_extra": [
    #'-bibcode:"keck"',
    'property:"refereed"'
  ],

  #Specific instrument assocations to look for
  "instruments": [
    'DEIMOS',
    'ESI',
    'HIRES',
    'KCWI',
    'LRIS',
    'MOSFIRE',
    'NIRC2',
    'NIRES',
    'NIRSPEC',
    'OSIRIS',
    'AO',
    'LGS',
    'NGS',
  ],

  # Dict of keywords to highlight in the title and abstract (color options: RED, GREEN, YELLOW, CYAN, PURPLE, CYAN)
  "colors": {
    'KECK': "GREEN",
    'DEIMOS': "CYAN",
    'ESI': "CYAN",
    'HIRES': "CYAN",
    'KCWI': "CYAN",
    'LRIS': "CYAN",
    'MOSFIRE': "CYAN",
    'NIRC2': "CYAN",
    'NIRES': "CYAN",
    'NIRSPEC': "CYAN",
    'OSIRIS': "CYAN",
    'LGS': "CYAN",
    'NGS': "CYAN",
    'AO': "CYAN",
  },

 
}

